/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface BlitzSavingsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deposit"
      | "depositFor"
      | "getBalance"
      | "getSavingsRule"
      | "removeSavingsRule"
      | "setSavingsRule"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "SavingsRuleRemoved"
      | "SavingsRuleSet"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "depositFor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSavingsRule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSavingsRule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setSavingsRule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "depositFor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSavingsRule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSavingsRule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSavingsRule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    newBalance: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, newBalance: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    newBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SavingsRuleRemovedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SavingsRuleSetEvent {
  export type InputTuple = [user: AddressLike, percentage: BigNumberish];
  export type OutputTuple = [user: string, percentage: bigint];
  export interface OutputObject {
    user: string;
    percentage: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    remaining: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, remaining: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    remaining: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlitzSavings extends BaseContract {
  connect(runner?: ContractRunner | null): BlitzSavings;
  waitForDeployment(): Promise<this>;

  interface: BlitzSavingsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deposit: TypedContractMethod<[], [void], "payable">;

  depositFor: TypedContractMethod<[user: AddressLike], [void], "payable">;

  getBalance: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getSavingsRule: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  removeSavingsRule: TypedContractMethod<[], [void], "nonpayable">;

  setSavingsRule: TypedContractMethod<
    [percentage: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "depositFor"
  ): TypedContractMethod<[user: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSavingsRule"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeSavingsRule"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSavingsRule"
  ): TypedContractMethod<[percentage: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "SavingsRuleRemoved"
  ): TypedContractEvent<
    SavingsRuleRemovedEvent.InputTuple,
    SavingsRuleRemovedEvent.OutputTuple,
    SavingsRuleRemovedEvent.OutputObject
  >;
  getEvent(
    key: "SavingsRuleSet"
  ): TypedContractEvent<
    SavingsRuleSetEvent.InputTuple,
    SavingsRuleSetEvent.OutputTuple,
    SavingsRuleSetEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Deposited(address,uint256,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "SavingsRuleRemoved(address)": TypedContractEvent<
      SavingsRuleRemovedEvent.InputTuple,
      SavingsRuleRemovedEvent.OutputTuple,
      SavingsRuleRemovedEvent.OutputObject
    >;
    SavingsRuleRemoved: TypedContractEvent<
      SavingsRuleRemovedEvent.InputTuple,
      SavingsRuleRemovedEvent.OutputTuple,
      SavingsRuleRemovedEvent.OutputObject
    >;

    "SavingsRuleSet(address,uint8)": TypedContractEvent<
      SavingsRuleSetEvent.InputTuple,
      SavingsRuleSetEvent.OutputTuple,
      SavingsRuleSetEvent.OutputObject
    >;
    SavingsRuleSet: TypedContractEvent<
      SavingsRuleSetEvent.InputTuple,
      SavingsRuleSetEvent.OutputTuple,
      SavingsRuleSetEvent.OutputObject
    >;

    "Withdrawn(address,uint256,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
